# Entrega 1 — desenho e configuração científica

**TCC: o que preservar os GEOs pode acrescentar ao Marketing Mix Modeling?**

Esta execução prepara e audita o painel e a especificação. Não estima a posterior nem resultados de marketing. A EDA já encontrou informação geotemporal, mas isso não comprova ganho causal ou preditivo. Vamos seguir uma sequência: origem → contrato → causalidade e especificação → priors → holdout → próximos experimentos → prontidão.

O guia completo é `docs/01_DESENHO_CIENTIFICO_DIDATICO.md`. O dataset é sintético, sem empresa, plataforma ou moeda identificadas. Não arredondamos conversões decimais. O objetivo desta sessão é verificar que a pergunta científica pode ser traduzida em entradas e decisões rastreáveis.

## 1. Preparação do ambiente

Em sessão Colab limpa, a próxima célula baixa **somente o repositório autorizado**. `REF` pode ser substituído pelo SHA da entrega para reprodução congelada; `main` serve para abrir a versão corrente e o SHA efetivo é impresso. A fonte dos dados é sempre um commit imutável com hash verificado. A instalação usa o lock do ambiente validado em Python 3.12. Se Colab pedir reinício, reinicie e execute novamente a partir desta célula. Localmente, o ambiente deve ter sido instalado pelos comandos do README; esta célula não instala nada fora do Colab.

In [1]:
import os, sys, subprocess
from pathlib import Path
REPOSITORY = 'https://github.com/thiagossilva17/MMM_Google_Meridian_ModelagemEtapa1.git'
REF = 'main'  # Para repetir a entrega, substitua pelo SHA informado no histórico.
IN_COLAB = 'google.colab' in sys.modules
if IN_COLAB:
    root = Path('/content/MMM_Google_Meridian_ModelagemEtapa1')
    if not root.exists():
        subprocess.run(['git', 'clone', REPOSITORY, str(root)], check=True)
    remote = subprocess.check_output(['git','-C',str(root),'remote','get-url','origin'],text=True).strip()
    assert remote == REPOSITORY, 'Remoto não autorizado'
    if REF != 'main':
        subprocess.run(['git','-C',str(root),'checkout','--detach',REF],check=True)
    os.chdir(root)
    subprocess.run([sys.executable,'-m','pip','install','-r','requirements-lock.txt'],check=True)
else:
    root = Path.cwd()
    if root.name == 'notebooks':
        root = root.parent
    assert (root/'configs/baseline_geo.yaml').exists(), 'Abra o notebook dentro do repositório'
    os.chdir(root)
sys.path.insert(0,str(root))
print('Python:',sys.version)
print('Diretório:',root)
head = subprocess.run(['git','rev-parse','HEAD'],capture_output=True,text=True)
print('Commit:',head.stdout.strip() if head.returncode == 0 else 'workspace local anterior à publicação')

Python: 3.12.14 (main, Aug 25 2026, 14:00:49) [Clang 22.1.3 ]
Diretório: /workspace/scratch/795adfbb054a/project
Commit: workspace local anterior à publicação

## 2. A origem vem antes dos números

A base oficial tem 40 mercados × 156 semanas. Não precisamos refazer a EDA; precisamos impedir que outra base entre silenciosamente. `verify_provenance` confere SHA-256, tamanho e Git blob. O CSV bruto é imutável. A cópia analítica só perde a coluna de índice após sua sequência ser validada.

O snapshot de dados e a release da API são commits distintos. O guia histórico não contém o hash da sua cópia do CSV: sua igualdade byte a byte continua não comprovada, embora estrutura e indicadores selecionados sejam comparáveis.

In [2]:
import json
from src.data_source import verify_provenance
from src.data_contract import load_panel, audit, structural_evidence
print('SHA-256 confirmado:',verify_provenance())
df = load_panel()
display(df.head())
display(audit(df))
print(json.dumps(structural_evidence(df),indent=2,ensure_ascii=False))

SHA-256 confirmado: d9ee016f7cd21f5c90b50da10a794af91a372b69f881d3caa266edd41fdafbf6
{
  "rows": 6240,
  "columns_clean": 19,
  "geos": 40,
  "weeks": 156,
  "date_min": "2021-01-25",
  "date_max": "2024-01-15",
  "population_kpi_corr": 0.9693338567456896,
  "between_kpi_fraction": 0.6788822241343846,
  "channel2_zero_fraction": 0.6426282051282052,
  "channel3_zero_fraction": 0.027083333333333334,
  "promo_zero_fraction": 0.46826923076923077,
  "channel2_spend_share": 0.05503310917455205,
  "channel3_spend_share": 0.4002888360053137,
  "population_once": 21696753.310000002,
  "fractional_conversions_preserved": true
}

    geo        time  ...  revenue_per_conversion  population
0  Geo0  2021-01-25  ...                0.020055   136670.94
1  Geo0  2021-02-01  ...                0.020103   136670.94
2  Geo0  2021-02-08  ...                0.019929   136670.94
3  Geo0  2021-02-15  ...                0.019987   136670.94
4  Geo0  2021-02-22  ...                0.020000   136670.94

[5 rows x 19 columns]

                       variable    dtype  ...         total  status
0           Channel0_impression    int64  ...  5.523420e+09    PASS
1           Channel1_impression    int64  ...  3.248579e+09    PASS
2           Channel2_impression    int64  ...  1.625551e+09    PASS
3           Channel3_impression    int64  ...  1.127450e+10    PASS
4           Channel4_impression    int64  ...  6.125671e+09    PASS
5                Channel0_spend  float64  ...  4.050171e+07    PASS
6                Channel1_spend  float64  ...  3.132030e+07    PASS
7                Channel2_spend  float64  ...  1.207935e+07    PASS
8                Channel3_spend  float64  ...  8.786036e+07    PASS
9                Channel4_spend  float64  ...  4.773068e+07    PASS
10     competitor_sales_control  float64  ... -2.771309e+02    PASS
11      sentiment_score_control  float64  ... -2.101326e+02    PASS
12  Organic_channel0_impression    int64  ...  3.322592e+09    PASS
13                        Promo  float64  ...  3.073375e+03    PASS
14                  conversions  float64  ...  6.593071e+10    PASS
15       revenue_per_conversion  float64  ...  1.248094e+02    PASS
16                   population  float64  ...  3.384694e+09    PASS

[17 rows x 8 columns]

## 3. Qual pergunta o modelo tentará responder?

A contribuição incremental futura compara a resposta esperada com a mídia observada à resposta esperada quando um canal é zerado, mantendo os demais fatores definidos. Só observamos uma história. A outra depende de pressupostos.

**DAG hipotético:** GEO/população e tempo influenciam demanda e KPI; demanda orienta investimento, Promo e orgânico; investimento determina exposição; exposição, orgânico e Promo podem influenciar KPI. Os índices podem ser proxies de demanda. Alternativamente, sentimento ou orgânico podem ser consequência da mídia: ajustá-los poderia remover mediação. Nenhum papel foi descoberto pela correlação.

Pressupostos: consistência da intervenção (unknown), ausência de confusão condicional (unsupported), positividade (partially assessable), não interferência (unknown), estabilidade temporal (assumed). O guia detalha o DAG e o registro. Na próxima entrega, boa convergência não converterá esses pressupostos em fatos.

Investigaremos precisão GEO/nacional, estabilidade a priors, heterogeneidade, atividade esparsa de C2, extrapolação de C3, tempo e papel dos controles. Não exigiremos que GEO vença.

DAG conceitual, explicitamente hipotético (o texto acima descreve as mesmas setas):

```mermaid
flowchart TD
  G["GEO e população"] --> D["Demanda latente"]
  T["Tempo"] --> D
  D --> I["Seleção de investimento"]
  I --> M["Exposição paga"]
  D --> Y["KPI"]
  G --> Y
  T --> Y
  M --> Y
  D --> C["Índices observados"]
  C --> I
  C --> Y
  D --> P["Promo"]
  P --> Y
  P --> I
  D --> O["Orgânico"]
  O --> Y
```

## 4. Traduzir variáveis sem mudar seu significado

`conversions` é o KPI contínuo não monetário. Impressões e gasto são pares por canal; gasto não entra como um segundo preditor duplicando exposição. População entra uma vez por GEO. Os controles preservam valores negativos. Promo preserva intensidade e zeros. Não há reach/frequency.

A API executável requer `non_revenue`, apesar de uma docstring escrever `non-revenue`. A configuração recebe valores brutos; as medidas por mil habitantes da EDA não substituem os dados de entrada. A célula abaixo constrói o objeto oficial, sem treinar.

In [3]:
import yaml
from src.meridian_setup import build_input, inspect_input, build_spec, prior_inventory, initialize_structure
input_data = build_input(df)
print(json.dumps(inspect_input(input_data,df),indent=2))
cfg = yaml.safe_load(Path('configs/baseline_geo.yaml').read_text())
display(cfg)
reference_spec = build_spec(input_data)
print('Prior paga ativa:',reference_spec.effective_media_prior_type)

{
  "kpi": {
    "shape": [
      40,
      156
    ],
    "dims": [
      "geo",
      "time"
    ]
  },
  "population": {
    "shape": [
      40
    ],
    "dims": [
      "geo"
    ]
  },
  "media": {
    "shape": [
      40,
      156,
      5
    ],
    "dims": [
      "geo",
      "media_time",
      "media_channel"
    ]
  },
  "media_spend": {
    "shape": [
      40,
      156,
      5
    ],
    "dims": [
      "geo",
      "time",
      "media_channel"
    ]
  },
  "controls": {
    "shape": [
      40,
      156,
      2
    ],
    "dims": [
      "geo",
      "time",
      "control_variable"
    ]
  },
  "organic_media": {
    "shape": [
      40,
      156,
      1
    ],
    "dims": [
      "geo",
      "media_time",
      "organic_media_channel"
    ]
  },
  "non_media_treatments": {
    "shape": [
      40,
      156,
      1
    ],
    "dims": [
      "geo",
      "time",
      "non_media_channel"
    ]
  }
}
Prior paga ativa: contribution

/workspace/scratch/795adfbb054a/venv/lib/python3.12/site-packages/meridian/data/input_data.py:605: UserWarning: Consider setting custom priors, as kpi_type was specified as `non_revenue` with no `revenue_per_kpi` being set. Otherwise, the total media contribution prior will be used with `p_mean=0.4` and `p_sd=0.2`. Further documentation available at https://developers.google.com/meridian/docs/advanced-modeling/unknown-revenue-kpi-custom#set-total-paid-media-contribution-prior
  warnings.warn(

{'version': '2.1.0',
 'source_commit': 'cb0be8fe454124aadb73222c579f081f8823edfd',
 'source_url': 'https://github.com/google/meridian/blob/cb0be8fe454124aadb73222c579f081f8823edfd/meridian/model/spec.py',
 'status': 'explicit_choice',
 'outcome': 'conversions',
 'kpi_type': 'non_revenue',
 'revenue_per_kpi': None,
 'revenue_policy': 'pending_decision',
 'scope': 'estrutura_sem_inferencia',
 'model_spec': {'media_prior_type': {'value': 'contribution',
   'status': 'explicit_choice',
   'reason': 'Evitar impor ROI monetário sem unidade validada; default Beta(1,99) exige revisão preditiva.'},
  'organic_media_prior_type': {'value': 'contribution',
   'status': 'verified_default',
   'reason': 'Default técnico, não conhecimento de negócio.'},
  'non_media_treatments_prior_type': {'value': 'contribution',
   'status': 'verified_default',
   'reason': 'Permite sinal positivo ou negativo na contribuição de Promo.'},
  'non_media_baseline_values': {'value': {'Promo': 0.0},
   'status': 'explicit_choice',
   'reason': 'Zero observado; intervenção de ausência proposta, sem significado causal comprovado.'},
  'media_effects_dist': {'value': 'log_normal',
   'status': 'verified_default',
   'reason': 'Pooling hierárquico com efeitos positivos; não admite danos da mídia neste baseline.'},
  'max_lag': {'value': 8,
   'status': 'verified_default',
   'reason': 'Oito semanas de defasagem, não duração demonstrada pela EDA.'},
  'hill_before_adstock': {'value': False,
   'status': 'verified_default',
   'reason': 'Acumula exposição antes de aplicar saturação.'},
  'adstock_decay_spec': {'value': 'geometric',
   'status': 'verified_default',
   'reason': 'Forma parsimoniosa, comparar binomial depois.'},
  'saturation_spec': {'value': 'hill',
   'status': 'verified_default',
   'reason': 'Retornos decrescentes; slope default fixo em 1.'},
  'unique_sigma_for_each_geo': {'value': False,
   'status': 'verified_default',
   'reason': 'Escala residual comum no espaço transformado; sensibilidade futura.'},
  'knots': {'value': None,
   'status': 'verified_default',
   'reason': '156 knots no GEO; não transportar silenciosamente ao nacional.'},
  'enable_aks': {'value': False,
   'status': 'verified_default',
   'reason': 'Mantém referência explícita; seleção de knots é experimento posterior.'},
  'baseline_geo': {'value': None,
   'status': 'verified_default',
   'reason': 'Referência de maior população, resolvida pela API.'},
  'population_scaled_controls': {'value': None,
   'status': 'explicit_choice',
   'reason': 'Índices com sinal, sem evidência de serem volumes extensivos.'},
  'population_scaled_non_media_channels': {'value': None,
   'status': 'explicit_choice',
   'reason': 'Promo tratada provisoriamente como intensidade contínua, não volume populacional.'}}}

## 5. Adstock, saturação, tempo e priors

Adstock representa memória: pesos geométricos até oito semanas. Hill representa saturação após essa acumulação; ec é meia saturação na escala interna e slope é fixo em 1. `log_normal` compartilha informação entre mercados impondo efeitos de mídia positivos. Uma escala residual comum é hipótese inicial.

`knots=None` significa 156 knots neste GEO, mas apenas um no nacional. AKS está desligado. Isso impede interpretar uma comparação futura de defaults como se só a geografia mudasse.

A prior paga escolhida é contribuição Beta(1,99), default com média 1% por canal: **não é neutra**, e sua adequação continua REVIEW. Orgânico também usa contribuição; Promo usa contribuição com sinal e baseline proposto zero. Não há prior baseada em ROI real ou lift.

O aviso de InputData sobre fallback de contribuição total é genérico. A especificação explícita paga usa contribuição por canal; campos ROI/R&F presentes no inventário não significam que estejam ativos. Aqui só inspecionamos distribuições, sem amostragem. Prior predictive será feito na Entrega 2, revendo KPI negativo, baseline, escala e saturação antes da posterior.

In [4]:
import pandas as pd
inventory = prior_inventory(reference_spec)
display(pd.DataFrame(inventory))

              parameter  ...                                         parameters
0           knot_values  ...                         {'loc': 0.0, 'scale': 5.0}
1   tau_g_excl_baseline  ...                         {'loc': 0.0, 'scale': 5.0}
2                beta_m  ...                                     {'scale': 5.0}
3               beta_rf  ...                                     {'scale': 5.0}
4               beta_om  ...                                     {'scale': 5.0}
5              beta_orf  ...                                     {'scale': 5.0}
6                 eta_m  ...                                     {'scale': 1.0}
7                eta_rf  ...                                     {'scale': 1.0}
8                eta_om  ...                                     {'scale': 1.0}
9               eta_orf  ...                                     {'scale': 1.0}
10              gamma_c  ...                         {'loc': 0.0, 'scale': 5.0}
11              gamma_n  ...                         {'loc': 0.0, 'scale': 5.0}
12                 xi_c  ...                                     {'scale': 5.0}
13                 xi_n  ...                                     {'scale': 5.0}
14              alpha_m  ...                          {'low': 0.0, 'high': 1.0}
15             alpha_rf  ...                          {'low': 0.0, 'high': 1.0}
16             alpha_om  ...                          {'low': 0.0, 'high': 1.0}
17            alpha_orf  ...                          {'low': 0.0, 'high': 1.0}
18                 ec_m  ...  {'loc': 0.8, 'scale': 0.8, 'low': 0.1, 'high':...
19                ec_rf  ...  {'distribution': tfp.distributions.LogNormal("...
20                ec_om  ...  {'loc': 0.8, 'scale': 0.8, 'low': 0.1, 'high':...
21               ec_orf  ...  {'distribution': tfp.distributions.LogNormal("...
22              slope_m  ...           {'loc': 1.0, 'atol': None, 'rtol': None}
23             slope_rf  ...                         {'loc': 0.7, 'scale': 0.4}
24             slope_om  ...           {'loc': 1.0, 'atol': None, 'rtol': None}
25            slope_orf  ...                         {'loc': 0.7, 'scale': 0.4}
26                sigma  ...                                     {'scale': 5.0}
27                roi_m  ...                         {'loc': 0.2, 'scale': 0.9}
28               roi_rf  ...                         {'loc': 0.2, 'scale': 0.9}
29               mroi_m  ...                         {'loc': 0.0, 'scale': 0.5}
30              mroi_rf  ...                         {'loc': 0.0, 'scale': 0.5}
31       contribution_m  ...  {'concentration1': 1.0, 'concentration0': 99.0...
32      contribution_rf  ...  {'concentration1': 1.0, 'concentration0': 99.0...
33      contribution_om  ...  {'concentration1': 1.0, 'concentration0': 99.0...
34     contribution_orf  ...  {'concentration1': 1.0, 'concentration0': 99.0...
35       contribution_n  ...  {'loc': 0.0, 'scale': 0.1, 'low': -1.0, 'high'...

[36 rows x 3 columns]

## 6. H-GEO: reservar informação sem escolher pelo resultado

O algoritmo usa apenas geo/time, seed 20261025 e seis GEOs por semana. Ele garante 15% do painel: 23 ou 24 semanas reservadas por GEO. A tabela completa é salva; a seed sozinha não substitui a máscara.

Somente o KPI dessas células sai da likelihood. Mídia histórica continua disponível para adstock. Não é um exercício de forecasting futuro. Balanceamento de células não garante equilíbrio de mídia: confira sobretudo atividade e gasto de Channel2.

In [5]:
from src.validation_design import make_holdout, coverage
validation = yaml.safe_load(Path('configs/validation_design.yaml').read_text())
h = validation['H-GEO']
split = make_holdout(df[['geo','time']],seed=h['seed'],per_week=h['per_week'])
by_geo, by_week, by_channel = coverage(df,split)
display(by_geo)
display(by_week.head())
display(by_channel.query("channel == 'Channel2'"))
holdout_spec = build_spec(input_data,split)
structure = initialize_structure(input_data,holdout_spec,split)
print('Estrutura inicializada sem inferência:',structure)

Estrutura inicializada sem inferência: {'initialization': 'PASS', 'n_knots': 156, 'resolved_holdout_count': 936}

      geo  sum  count  fraction
0    Geo0   23    156  0.147436
1    Geo1   24    156  0.153846
2   Geo10   23    156  0.147436
3   Geo11   23    156  0.147436
4   Geo12   23    156  0.147436
5   Geo13   24    156  0.153846
6   Geo14   23    156  0.147436
7   Geo15   23    156  0.147436
8   Geo16   24    156  0.153846
9   Geo17   24    156  0.153846
10  Geo18   23    156  0.147436
11  Geo19   23    156  0.147436
12   Geo2   24    156  0.153846
13  Geo20   24    156  0.153846
14  Geo21   24    156  0.153846
15  Geo22   23    156  0.147436
16  Geo23   23    156  0.147436
17  Geo24   23    156  0.147436
18  Geo25   23    156  0.147436
19  Geo26   24    156  0.153846
20  Geo27   23    156  0.147436
21  Geo28   24    156  0.153846
22  Geo29   24    156  0.153846
23   Geo3   23    156  0.147436
24  Geo30   23    156  0.147436
25  Geo31   23    156  0.147436
26  Geo32   23    156  0.147436
27  Geo33   24    156  0.153846
28  Geo34   23    156  0.147436
29  Geo35   24    156  0.153846
30  Geo36   24    156  0.153846
31  Geo37   24    156  0.153846
32  Geo38   23    156  0.147436
33  Geo39   24    156  0.153846
34   Geo4   23    156  0.147436
35   Geo5   24    156  0.153846
36   Geo6   23    156  0.147436
37   Geo7   23    156  0.147436
38   Geo8   23    156  0.147436
39   Geo9   23    156  0.147436

         time  sum  count  fraction
0  2021-01-25    6     40      0.15
1  2021-02-01    6     40      0.15
2  2021-02-08    6     40      0.15
3  2021-02-15    6     40      0.15
4  2021-02-22    6     40      0.15

      geo   channel subset  ...  active_fraction   impressions         spend
4     ALL  Channel2  train  ...         0.356523  1.378170e+09  1.024108e+07
5     ALL  Channel2   test  ...         0.362179  2.473816e+08  1.838274e+06
14   Geo0  Channel2  train  ...         0.360902  8.948100e+06  6.649265e+04
15   Geo0  Channel2   test  ...         0.260870  1.092485e+06  8.118173e+03
24   Geo1  Channel2  train  ...         0.371212  1.433781e+07  1.065432e+05
..    ...       ...    ...  ...              ...           ...           ...
385  Geo7  Channel2   test  ...         0.478261  1.151555e+07  8.557119e+04
394  Geo8  Channel2  train  ...         0.323308  1.961748e+07  1.457760e+05
395  Geo8  Channel2   test  ...         0.173913  1.449645e+06  1.077220e+04
404  Geo9  Channel2  train  ...         0.270677  2.949965e+07  2.192097e+05
405  Geo9  Channel2   test  ...         0.608696  1.322496e+07  9.827368e+04

[82 rows x 9 columns]

## 7. H-COMP e nacional: decisões que continuam abertas

H-GEO não é holdout nacional equivalente: a soma nacional pode incluir KPI de células reservadas. R² de células e de somas também são unidades diferentes.

H-COMP está PENDING_METHOD_DECISION. Reservar semanas internas iguais nos dois modelos é candidato, mas deixar todos os GEOs de uma semana fora prejudica seu knot. Antes de executar, definir knots com suporte no treino e auditar uso indireto do KPI em seleção, transformação e priors.

O plano nacional soma KPI, impressões e gasto por semana e população uma vez por GEO. Receita por conversão seria ponderada por conversões. Os dois índices e Promo exigem uma hipótese de agregação: média populacional se intensidade, outra regra se sua semântica exigir. Somar índices por conveniência não resolve isso. Nenhum MMM nacional será criado aqui.

In [6]:
print(json.dumps(validation['H-COMP'],indent=2,ensure_ascii=False))
registry = yaml.safe_load(Path('configs/experiment_registry.yaml').read_text())
assert all(e['status']=='planned' for e in registry['experiments'])
display(pd.DataFrame(registry['experiments'])[['id','stage','status','hypothesis','factor_changed','required_gate']])

{
  "status": "PENDING_METHOD_DECISION",
  "candidate": "Semanas internas não contíguas iguais nos dois modelos, mantendo extremos no treino.",
  "fraction_proposed": 0.1,
  "seed_proposed": 20261026,
  "shared_scale": "Soma nacional de conversões por semana.",
  "required_before_execution": [
    "Definir knots interpoláveis com suporte no treino, iguais em desenho controlado quando viável.",
    "Não usar o KPI das semanas de teste para seleção de knots ou tuning.",
    "Auditar escala/priors dependentes do KPI e eventual uso indireto do teste.",
    "Fixar agregação dos índices e Promo com justificativa semântica.",
    "Separar comparação operacional de defaults da comparação metodológica controlada."
  ],
  "prohibited": "Comparar R2 das células GEO com R2 de totais nacionais; usar H-GEO como teste nacional equivalente."
}

               id  ...          required_gate
0              G0  ...       sampling_healthy
1              G1  ...           fit_reviewed
2              N0  ...       sampling_healthy
3              P1  ...     inference_reviewed
4              P2  ...     inference_reviewed
5              P3  ...     inference_reviewed
6              P4  ...     inference_reviewed
7              A1  ...     inference_reviewed
8              A2  ...     inference_reviewed
9              A3  ...     inference_reviewed
10             A4  ...     inference_reviewed
11             K1  ...     inference_reviewed
12             K2  ...     inference_reviewed
13             K3  ...     inference_reviewed
14             K4  ...     inference_reviewed
15             C1  ...     inference_reviewed
16             C2  ...     inference_reviewed
17             C3  ...     inference_reviewed
18      C2_SPARSE  ...     inference_reviewed
19  C3_CONTINUOUS  ...     inference_reviewed
20        GEO_HET  ...     inference_reviewed
21        GEO_NAT  ...     inference_reviewed
22      INFLUENCE  ...     inference_reviewed
23             F0  ...     inference_reviewed
24             O0  ...  optimization_eligible

[25 rows x 6 columns]

## 8. Executar a auditoria completa e ler seu alcance

Os gates futuros são dados → especificação → amostragem saudável → ajuste revisado → inferência revisada → eventual elegibilidade de otimização. Nesta etapa só há verificação técnica dos dois primeiros. R-hat, ESS, PPC e métricas de ajuste não existem ainda.

A execução abaixo salva as auditorias, a máscara, priors configuradas e o manifesto. Os seis alertas locais de C2 devem continuar REVIEW. A primeira falha de API foi registrada e corrigida; não se ocultam erros de construção.

In [7]:
from src.run_stage1 import run
manifest = run()
print(json.dumps(manifest,indent=2,ensure_ascii=False))
display(json.loads(Path('outputs/tables/holdout_review.json').read_text()))

{
  "executed_at_utc": "2026-10-25T11:46:05.192613+00:00",
  "scope": "Entrega 1: validação e configuração apenas",
  "data_ready": "PASS",
  "spec_ready": "PASS",
  "scientific_readiness": "REVIEW",
  "holdout_status": "REVIEW",
  "holdout_train": 5304,
  "holdout_test": 936,
  "H_COMP": "PENDING_METHOD_DECISION",
  "hosted_colab": "NOT_TESTED_IN_HOSTED_COLAB",
  "posterior_sampling_executed": false,
  "prior_sampling_executed": false,
  "roi_estimated": false,
  "national_model_constructed": false,
  "source_sha256": "d9ee016f7cd21f5c90b50da10a794af91a372b69f881d3caa266edd41fdafbf6",
  "python": "3.12.14",
  "versions": {
    "google-meridian": "2.1.0",
    "numpy": "2.3.5",
    "pandas": "2.3.3",
    "tensorflow": "2.21.0",
    "tfp-nightly": "0.26.0.dev20260130",
    "jax": "0.12.0.1",
    "PyYAML": "6.0.3",
    "pytest": "9.1.1",
    "nbformat": "5.11.1",
    "nbclient": "0.11.0",
    "ipykernel": "7.4.0"
  },
  "artifact_sha256": {
    "outputs/tables/data_audit.csv": "f7deea34fb44612735395a23ca85c83eee7b80091f147c9520fddd6473d120a3",
    "outputs/tables/eda_reconciliation.json": "34297321dce70dbd341f2af5e07afe91942b7ddd555e5315eb26b09737b055cb",
    "outputs/tables/holdout_by_channel_geo.csv": "f49fada2824943136a5500ff5c339beaebe2573133d4f4cca8cc3e30dfd1fe6a",
    "outputs/tables/holdout_by_geo.csv": "0c505f00cd3204f752a393fb84cd5049e91428a9d9b03a06f8531d46453bff7b",
    "outputs/tables/holdout_by_week.csv": "9d2fe590aa09ab5ed2dffd63d4c4ad15f93bc38ca4ed5f1e6866732aa22f7202",
    "outputs/tables/holdout_review.json": "a9fcc85d83e241047e410a71e2f3e845c5a9a29a029cc5a41efe9222a60618f5",
    "outputs/tables/prior_inventory.json": "92ccfa0f0d158171431e015bb744707bd58a5e996fb38363fa5a1621c2f9623b",
    "outputs/tables/structural_evidence.json": "21a634f15cdf0401ba5717b9e890eade06dac9e6a7b3ce8afe5bccf927189a54",
    "data/splits/holdout_geo.csv": "dc1da829931b05e60f0df2834f9c06d5408c20036f08e4599ca7e1c0827e9990"
  }
}

/workspace/scratch/795adfbb054a/venv/lib/python3.12/site-packages/meridian/data/input_data.py:605: UserWarning: Consider setting custom priors, as kpi_type was specified as `non_revenue` with no `revenue_per_kpi` being set. Otherwise, the total media contribution prior will be used with `p_mean=0.4` and `p_sd=0.2`. Further documentation available at https://developers.google.com/meridian/docs/advanced-modeling/unknown-revenue-kpi-custom#set-total-paid-media-contribution-prior
  warnings.warn(

{'status': 'REVIEW',
 'alerts': ['Geo13/Channel2: diferença de atividade >20pp',
  'Geo29/Channel2: fração de gasto teste 0.0482 fora de [0.05,0.30]',
  'Geo29/Channel2: diferença de atividade >20pp',
  'Geo32/Channel2: fração de gasto teste 0.0497 fora de [0.05,0.30]',
  'Geo9/Channel2: fração de gasto teste 0.3095 fora de [0.05,0.30]',
  'Geo9/Channel2: diferença de atividade >20pp'],
 'action': 'Preservar máscara; investigar desequilíbrios antes de interpretar desempenho local.'}

## 9. Testes e encerramento da etapa

Os testes introduzem duplicações, ausências, população variável e pares quebrados para conferir rejeição; verificam imutabilidade, máscara independente do KPI, reconciliação de cobertura e integração real com Meridian. A suíte não instala pacotes nem ajusta modelos.

Uma execução local não comprova a interface hospedada do Colab. O campo NOT_TESTED_IN_HOSTED_COLAB permanece até registrar uma execução real em sessão limpa com evidência revisada; não é atualizado automaticamente só por abrir este notebook.

In [8]:
result = subprocess.run([sys.executable,'-m','pytest','-q'],capture_output=True,text=True)
print(result.stdout)
if result.returncode:
    print(result.stderr)
    raise RuntimeError('BLOCKED: testes falharam')
print('PASS técnico: fonte, painel, InputData, ModelSpec e máscara verificados.')
print('REVIEW científico: priors, suporte local, pressupostos e uso indireto de KPI reservado.')
print('H-COMP: PENDING_METHOD_DECISION')
print('Colab hospedado: NOT_TESTED_IN_HOSTED_COLAB no registro original; anexar evidência para encerrá-lo.')
print('Fim da Entrega 1. Nenhuma posterior, ROI, mROI ou otimização foi executada.')

....................                                                     [100%]
=============================== warnings summary ===============================
tests/test_stage1.py::test_meridian_input_spec_resolved_mask
  /workspace/scratch/795adfbb054a/venv/lib/python3.12/site-packages/meridian/data/input_data.py:605: UserWarning: Consider setting custom priors, as kpi_type was specified as `non_revenue` with no `revenue_per_kpi` being set. Otherwise, the total media contribution prior will be used with `p_mean=0.4` and `p_sd=0.2`. Further documentation available at https://developers.google.com/meridian/docs/advanced-modeling/unknown-revenue-kpi-custom#set-total-paid-media-contribution-prior
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
20 passed, 1 warning in 10.63s

PASS técnico: fonte, painel, InputData, ModelSpec e máscara verificados.
REVIEW científico: priors, suporte local, pressupostos e uso indireto de KPI reservado.
H-COMP: PENDING_METHOD_DECISION
Colab hospedado: NOT_TESTED_IN_HOSTED_COLAB no registro original; anexar evidência para encerrá-lo.
Fim da Entrega 1. Nenhuma posterior, ROI, mROI ou otimização foi executada.